using System;
using System.Collections.Generic;
namespace WateralGenNHibernate.EN.Wateral
{
public class ProfesorEN_OID
{
private string nIF;
public virtual string NIF {
        get { return nIF; } set { nIF = value;  }
}




private int id;
public virtual int Id {
        get { return id; } set { id = value;  }
}






public ProfesorEN_OID()
{
}
public ProfesorEN_OID(string NIF, int id)
{
        this.NIF = NIF;
        this.id = id;
}

public override bool Equals (object obj)
{
        if (obj == null)
                return false;
        ProfesorEN_OID t = obj as ProfesorEN_OID;
        if (t == null)
                return false;


        if (this.nIF == t.NIF && this.id == t.Id)

                return true;
        else
                return false;
}

public override int GetHashCode ()
{
        int hash = 13;

        // Su tipo es String
        hash = hash +
               (null == nIF                                                      ? 0 : this.nIF.GetHashCode ());
        // Su tipo es Autogenerated
        hash = hash +
               (0 == id                                                 ? 0 : this.id.GetHashCode ());
        return hash;
}
}
}
